#!/bin/sh -ex
tmp=$(git-hooks-workdir "$@")
trap 'rm -rf "$tmp"' INT TERM EXIT HUP

cd "$tmp/doc"

notwiki-doc html "/srv/http/vhost/code/sni-shunt" .
notwiki-doc gph  "/srv/gopher/sni-shunt" .
notwiki-mandoc gph utf8 "/srv/gopher/man" .
notwiki-mandoc html html "/srv/http/vhost/code/man" .
cp "style.css" "/srv/http/vhost/code"
